// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using MvcStarter.Data;

#nullable disable

namespace MvcStarter.Migrations
{
    [DbContext(typeof(TodoDbContext))]
    [Migration("20260815120718_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.19");

            modelBuilder.Entity("MvcStarter.Models.TodoItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsCompleted")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Todos");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            IsCompleted = true,
                            Title = "Learn C#"
                        },
                        new
                        {
                            Id = 2,
                            IsCompleted = false,
                            Title = "Build MVC app"
                        },
                        new
                        {
                            Id = 3,
                            IsCompleted = false,
                            Title = "Go for a walk"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
